[env:d1_mini]
platform = espressif8266@4.2.1
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@6.21.5
  duinowitchery/hd44780@1.3.2
  aircoookie/Espalexa@2.7.0
