#pragma once
#include <Arduino.h>
const char PAGE[] PROGMEM=R"HTML(<!doctype html>
<html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orologio WiFi</title>
<style>:root{font-family:system-ui,sans-serif;color:#e5edf7;background:#101724;color-scheme:dark}body{max-width:850px;margin:auto;padding:24px}h1{margin-bottom:5px}p{color:#aabbd1;line-height:1.5}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}section{background:#1b2638;border:1px solid #344359;border-radius:18px;padding:22px;margin:18px 0}label{display:block;margin:15px 0 6px}input,select,button{font:inherit;border-radius:9px;border:1px solid #52637a;padding:11px;box-sizing:border-box}input:not([type=checkbox]),select{width:100%;background:#111c2c}button{background:#83d9bc;color:#10251f;font-weight:650;cursor:pointer;margin-top:14px}button.secondary{background:#293b53;color:#e5edf7}input[type=checkbox]{width:18px;height:18px}#time{font-size:clamp(25px,5vw,42px);font-variant-numeric:tabular-nums}#message{position:sticky;bottom:12px;background:#23453e;border-radius:12px;padding:14px;white-space:pre-wrap}small{color:#aabbd1}ul{padding-left:18px}li button{padding:5px;margin:5px 0 5px 12px;font-size:13px}footer{font-size:13px;color:#aabbd1}button:disabled{opacity:.5}</style>
<h1>Orologio WiFi</h1><p>Un piccolo orologio, come piace a te.</p>
<section><div id="time">Collegamento…</div><p id="state"></p><small id="ntp"></small></section>
<div class="grid"><section><h2>Ora e display</h2><form id="settings"><label for="mode">Regolazione dell'ora</label><select id="mode" name="auto"><option value="1">Automatica · NTP ogni 15 minuti</option><option value="0">Manuale</option></select>
<label for="zone">Fuso orario</label><select id="zone" name="zone"><option value="0">Italia · Europe/Rome</option><option value="1">UTC</option><option value="2">Londra · Europe/London</option><option value="3">New York</option><option value="4">Los Angeles</option><option value="5">Tokyo</option></select><small>Ora legale automatica dove prevista.</small>
<label for="font">Stile delle cifre</label><select name="font" id="font"><option value="0">Grande · pieno (16×2)</option><option value="1">Grande · sottile (16×2)</option><option value="2">Compatto · con secondi</option><option value="3">Slanciato · 1×2</option><option value="4">Trek · 2×2</option><option value="5">Classico · 3×2</option><option value="6">Arrotondato · 3×2</option><option value="7">Geometrico · 3×2</option></select>
<label for="dots">Puntini separatori</label><select id="dots" name="dots"><option value="0">Lampeggianti</option><option value="1">Fissi</option><option value="2">Disattivati</option></select>
<label><input type="checkbox" id="date"> Mostra anche la data</label><label><input type="checkbox" id="year"> Mostra l’anno nella data</label><label for="every">Mostra la data dopo quanti secondi di orologio?</label><input id="every" name="every" type="number" min="5" max="3600" required value="20"><label for="duration">Durata della data (secondi)</label><input id="duration" name="duration" type="number" min="2" max="60" required value="5"><button>Salva impostazioni</button></form><button id="sync" class="secondary">Aggiorna NTP adesso</button>
<form id="manual"><label for="local">Data e ora nel fuso selezionato</label><input type="datetime-local" id="local" name="local" step="1" required min="2024-01-01T00:00" max="2099-12-31T23:59:59"><button>Imposta ora manuale</button></form><p><small>Senza batteria o RTC, dopo aver tolto alimentazione l'ora va recuperata da Internet oppure impostata di nuovo.</small></p></section>
<section><h2>Luminosità</h2><form id="light"><label for="lightMode">Modalità</label><select id="lightMode"><option value="0">Fissa</option><option value="1">Automatica per fasce orarie</option></select><label for="brightness">Luminosità fissa · <output id="brightnessValue">100%</output></label><input id="brightness" type="range" min="0" max="100" step="5" value="100"><p>Ogni fascia inizia all'ora indicata e dura fino alla successiva, anche oltre mezzanotte. Usa il fuso orario dell'orologio.</p><div id="bands"></div><button type="button" class="secondary" id="addBand">Aggiungi fascia</button><br><button>Salva luminosità</button></form><p><small>0% spegne la luce. Durante la configurazione la luce resta al 100%. Finché l'ora non è disponibile, le fasce non vengono applicate.</small></p><small id="effective"></small></section><section><h2>Alexa</h2><form id="alexa"><label><input type="checkbox" id="alexaEnabled"> Abilita il controllo con Alexa</label><label for="alexaName">Nome del dispositivo</label><input id="alexaName" maxlength="32" required value="Orologio"><small>Esempi: “Orologio”, “Orologio cucina”. Dopo il salvataggio il dispositivo si riavvia; avvia quindi “Cerca dispositivi” nell'app Alexa.</small><br><button>Salva Alexa</button></form><p id="alexaState"></p><small>Un comando Alexa di accensione, spegnimento o luminosità passa il display alla modalità fissa e salva il livello scelto.</small></section><section><h2>Connessione Wi-Fi</h2><p>Reti a 2,4 GHz. Le ultime tre connessioni riuscite vengono ricordate, dalla più recente.</p><button id="scan" class="secondary">Cerca reti</button><label for="found">Reti disponibili</label><select id="found"><option value="">Scegli o inserisci il nome sotto</option></select><form id="wifi"><label for="ssid">Nome rete (SSID)</label><input id="ssid" name="ssid" maxlength="32" required autocomplete="off"><label for="password">Password Wi-Fi</label><input id="password" name="password" type="password" maxlength="64" autocomplete="new-password"><small>Lascia vuoto per una rete aperta.</small><br><button>Collega alla rete</button></form><h3>Reti ricordate</h3><ul id="networks"></ul><p id="error"></p><small>Se la connessione fallisce, l'AP resta disponibile a 192.168.4.1. Nome e password scorrono sul display. Se il telefono segnala “nessuna connessione Internet”, resta connesso all'AP.</small></section></div><div id="message" role="status" hidden></div><footer>Il pannello è accessibile ai dispositivi della tua rete locale. Le password Wi-Fi non vengono restituite dal pannello.</footer>
<script>
const $=id=>document.getElementById(id);let loaded=false,busy=false;
function message(t){$('message').textContent=t;$('message').hidden=false}
async function post(path,data={}){let r=await fetch('/api/'+path,{method:'POST',headers:{'X-Orologio':'1'},body:new URLSearchParams(data)});let j=await r.json();if(!r.ok)throw Error(j.message);message(j.message);return j}
async function guarded(fn){try{await fn()}catch(e){message(e.message||'Collegamento interrotto. Controlla l’IP sul display.')}}
async function status(){try{let r=await fetch('/api/status');let s=await r.json();$('time').textContent=s.time;$('state').textContent=s.connected?`${s.ssid} · ${s.ip}`:s.connecting?'Connessione Wi-Fi in corso…':'Modalità configurazione AP · 192.168.4.1';$('ntp').textContent='NTP: '+s.ntp+(s.lastNtp?' · Ultimo successo: '+new Date(s.lastNtp*1000).toLocaleString('it-IT',{timeZone:s.zoneName}):'');$('error').textContent=s.error+(!s.storage?' · Errore memoria persistente':'')+(!s.lcd?' · Display I²C non rilevato':'');if(!loaded){$('lightMode').value=s.lightAuto?'1':'0';$('brightness').value=s.brightness;$('brightnessValue').textContent=s.brightness+'%';$('bands').replaceChildren();s.bands.forEach(addBand);$('mode').value=s.auto?'1':'0';$('zone').value=s.zone;$('font').value=s.font;$('date').checked=s.date;$('year').checked=s.year;$('dots').value=s.dots;$('every').value=s.every;$('duration').value=s.duration;$('alexaEnabled').checked=s.alexaEnabled;$('alexaName').value=s.alexaName;loaded=true} $('effective').textContent='Luminosità attuale: '+s.effectiveBrightness+'%';$('alexaState').textContent=s.alexaEnabled?(s.alexaReady?'Alexa attiva come “'+s.alexaName+'”':'Alexa abilitata; in attesa della rete Wi-Fi'):'Alexa disattivata';$('networks').replaceChildren();s.networks.forEach(n=>{let li=document.createElement('li');li.append(document.createTextNode(n));let b=document.createElement('button');b.textContent='Dimentica';b.className='secondary';b.onclick=()=>guarded(async()=>{await post('forget',{ssid:n});await status()});li.append(b);$('networks').append(li)});$('sync').disabled=!s.auto||!s.connected;document.querySelector('#manual button').disabled=s.auto}catch(e){$('state').textContent='Pannello non raggiungibile: controlla rete e IP sul display.'}}
function addBand(b={minute:720,level:50}){if($('bands').children.length>=6){message('Massimo 6 fasce');return}let row=document.createElement('div');row.style.cssText='display:flex;gap:8px;align-items:center;margin:10px 0';let t=document.createElement('input');t.type='time';t.required=true;t.value=String(Math.floor(b.minute/60)).padStart(2,'0')+':'+String(b.minute%60).padStart(2,'0');t.setAttribute('aria-label','Inizio fascia');let l=document.createElement('input');l.type='number';l.min=0;l.max=100;l.required=true;l.value=b.level;l.setAttribute('aria-label','Luminosità percentuale');let remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='×';remove.setAttribute('aria-label','Rimuovi fascia');remove.onclick=()=>row.remove();row.append(t,l,document.createTextNode('%'),remove);$('bands').append(row)}
$('brightness').oninput=()=>{$('brightnessValue').textContent=$('brightness').value+'%'};$('addBand').onclick=()=>addBand();
$('light').onsubmit=e=>{e.preventDefault();guarded(async()=>{let bands=Array.from($('bands').children).map(row=>{let inputs=row.querySelectorAll('input');let [h,m]=inputs[0].value.split(':').map(Number);return {minute:h*60+m,level:Number(inputs[1].value)}});let r=await fetch('/api/light',{method:'POST',headers:{'X-Orologio':'1','Content-Type':'application/json'},body:JSON.stringify({lightAuto:$('lightMode').value==='1',brightness:Number($('brightness').value),bands})});let d=await r.json();if(!r.ok)throw Error(d.message);message(d.message);await status()})};
$('alexa').onsubmit=e=>{e.preventDefault();guarded(()=>post('alexa',{enabled:$('alexaEnabled').checked?'1':'0',name:$('alexaName').value}))};
$('settings').onsubmit=e=>{e.preventDefault();guarded(async()=>{let data=Object.fromEntries(new FormData(e.target));data.date=$('date').checked?'1':'0';data.year=$('year').checked?'1':'0';await post('settings',data);await status()})};$('manual').onsubmit=e=>{e.preventDefault();guarded(()=>post('time',Object.fromEntries(new FormData(e.target))))};$('wifi').onsubmit=e=>{e.preventDefault();guarded(async()=>{await post('wifi',Object.fromEntries(new FormData(e.target)));$('password').value=''})};$('sync').onclick=()=>guarded(()=>post('sync'));$('found').onchange=()=>{$('ssid').value=$('found').value};$('scan').onclick=()=>guarded(async()=>{if(busy)return;busy=true;$('scan').disabled=true;try{for(let i=0;i<20;i++){let r=await fetch('/api/scan');if(r.status===202){await new Promise(r=>setTimeout(r,800));continue}let a=await r.json();$('found').replaceChildren(new Option('Scegli una rete',''));let seen=new Set();a.sort((a,b)=>b.rssi-a.rssi).forEach(n=>{if(!n.ssid||seen.has(n.ssid))return;seen.add(n.ssid);$('found').add(new Option(`${n.ssid} (${n.rssi} dBm${n.open?', aperta':''})`,n.ssid))});return}throw Error('Scansione non conclusa: riprova')}finally{busy=false;$('scan').disabled=false}});status();setInterval(status,2500);
</script></html>)HTML";
